import { Plus_Jakarta_Sans, Geist, Geist_Mono } from "next/font/google"; // Import the desired font
import "../../styles/globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "../../components/Layout/Header";
import Footer from "../../components/Layout/Footer";
import StoreProvider from "./StoreProvider";

// Use next/font/google to import Plus Jakarta Sans
const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

// Use Geist and Geist_Mono as needed
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable} ${geistSans.variable} ${geistMono.variable}`}
      >
        <StoreProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
